### ISSUE TITLE
Some problem I meet in Mc

### ISSUE THREAD

**Issue by sora20483154569** [starfish-studios/Hamsters#3]
My English is not good,I use Translator to show my trouble.
I only put the mod,Hamsters,into my Mc and I finded that I cannot climb ladder , staging and the others like them.
Hope that the problem will be solved.
Game Version: 1.20.1 Fabric 0.15.3
Mod Version:1.0.0 Fabric

**Comment by crispytwig** [comment]
This was fixed in 1.0.1. Apologies for the late response!
