### ISSUE TITLE
Clarify licence

### ISSUE THREAD

**Issue by ghostdevv** [starfish-studios/Hamsters#4]
The new license added in 8b38dadd4bafa4e730a34b573bdf30a207de3eef reserves all rights to `/fabric/src/main/resources/` (which doesn't exist so I am *assuming* you meant `/src/main/resources/`) is it possible to clarify that? Specifically we would like to make some changes to the mod and would like to distribute those changes to friends. Could you clarify in the license what (if anything) you will permit, or consider switching the entire codebase to [MIT which allows for everything we would need](https://choosealicense.com/licenses/mit/) but still gives you your copyright - you could also consider a license such as [GPL v3](https://choosealicense.com/licenses/gpl-3.0/).

**Comment by crispytwig** [comment]
That's my bad -- the license was derived from our Architectury-based license where there are multiple loaders present. You may make changes if only distributing to friends, but public redistribution of our assets is not allowed. Thanks for asking!
