### ISSUE TITLE
Hamsters extreme spawn rate

### ISSUE THREAD

**Issue by King-Friendly** [starfish-studios/Hamsters#5]
In the tundra biome, hamsters FILL the surrounding region. Like I use Xaeros minimap and it's ALL yellow dots.

![image](https://github.com/starfish-studios/Hamsters/assets/146692647/f6a9f1d8-38ef-43f7-acf5-2e7e78468037)
![image](https://github.com/starfish-studios/Hamsters/assets/146692647/ca00c736-ec09-49a9-9a58-4a75fd193cf8)

**Comment by crispytwig** [comment]
Can you please post your latest.log and a screenshot of your mod folder in list view? We've had this issue with a couple of our other mods and it only ever happens when in a modpack, and I haven't been able to pinpoint what mod is causing it.

**Comment by crispytwig** [comment]
Feel free to create another ticket if you revisit this -- closing it for now with the note that we've encountered this issue when using mods like Respawning Animals.
