### ISSUE TITLE
Hamsters (hamsters) has failed to load correctly

### ISSUE THREAD

**Issue by anomyq** [starfish-studios/Hamsters#7]
[Crash-Report.txt](https://github.com/starfish-studios/Hamsters/files/14180982/Crash-Report.txt)
[latest.log.txt](https://github.com/starfish-studios/Hamsters/files/14180989/latest.log.txt)

**Comment by crispytwig** [comment]
You do not have GeckoLib. You need GeckoLib. Add GeckoLib.
