### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by mangoharu** [starfish-studios/Hamsters#9]
![1](https://github.com/starfish-studios/Hamsters/assets/160516066/c75d93bf-1f06-41d8-a2b0-4c5707222db0)

Please understand that I am not good at English so I am using a translator.

I kept getting errors so I just turned on hamster mode.
There are no other modes
The error keeps appearing
Forge version is 47.2.20
How can I solve this problem?

**Comment by crispytwig** [comment]
Install this as well -- the mod won't work without it. https://www.curseforge.com/minecraft/mc-mods/geckolib/files/5060416
